name: build-binaries
on: workflow_dispatch

jobs:

  create-executables:
    name: Create executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows

    steps:
      - name: "get code"
        uses: actions/checkout@v2

      - name: "setup environment"
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
          architecture: x86

      - name: "install dependencies"
        run: python3 -m pip install -r requirements.txt && python3 -m pip install pyinstaller

      - name: "build"
        run: cd src && pyinstaller -F --name "Beat N Boom" main.py

      - name: "upload"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: dist/