name: Compile-Executables
on:
  workflow_dispatch:
    inputs:
      disable-console:
        description: 'if enabled then no console will be there in windows and mac'
        required: false
        default: 'y'

jobs:

  create-executables:
    name: Create executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:

          - os: windows-latest
            TARGET: "windows 32 bit"
            file-copy-command: mkdir src\dist\assets && xcopy src\assets src\dist\assets /s
            architecture: x86
            cachepath: ~\AppData\Local\pip\Cache
            pyinstaller-options: --add-data "c:/hostedtoolcache/windows/python/3.7.9/x86/lib/site-packages/librosa/util/example_data/registry.txt;registry.txt"

          - os: windows-latest
            TARGET: "windows 64 bit"
            file-copy-command: mkdir src\dist\assets && xcopy src\assets src\dist\assets /s
            architecture: x64
            cachepath: ~\AppData\Local\pip\Cache
            pyinstaller-options: --add-data "c:/hostedtoolcache/windows/python/3.7.9/x64/lib/site-packages/librosa/util/example_data/registry.txt;registry.txt"

          - os: macos-latest
            TARGET: mac
            file-copy-command: mkdir src/dist/assets && cp -a src/assets/. src/dist/assets/
            architecture: x64
            cachepath: ~/Library/Caches/pip
            pyinstaller-options: --add-data /Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/librosa/util/example_data/registry.txt:librosa/util/example_data/registry.txt

          - os: ubuntu-latest
            TARGET: "linux 64 bit"
            file-copy-command: mkdir src/dist/assets && cp -a src/assets/. src/dist/assets/
            architecture: x64
            cachepath: ~/.cache/pip
            pyinstaller-options: --add-data /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/librosa/util/example_data/:librosa/util/example_data/

    steps:
      - name: "get code"
        uses: actions/checkout@v2

      - name: "setup environment"
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
          architecture: ${{matrix.architecture}}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ matrix.TARGET }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ matrix.TARGET }}-pip-

      - name: "install dependencies"
        run: python3 -m pip install -r requirements.txt && python3 -m pip install pyinstaller wheel

      - name: "build"
        if: ${{ github.event.inputs.disable-console == 'y'}}
        run: cd src/ && pyinstaller -F --name "Beat N Boom" --windowed ${{ matrix.pyinstaller-options }} --hidden-import="sklearn.utils._weight_vector" main.py

      - name: "build (with console)"
        if: !${{ github.event.inputs.disable-console == 'y'}}
        run: cd src/ && pyinstaller -F --name "Beat N Boom" ${{ matrix.pyinstaller-options }} --hidden-import="sklearn.utils._weight_vector" main.py

      - name: "Compress Executable"
        uses: svenstaro/upx-action@v2
        with:
          file: src/dist/mything

      - name: "copy other files"
        run: ${{ matrix.file-copy-command }}

      - name: "upload"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: src/dist/
